### ISSUE TITLE
[Errno 13] Permission denied: b'./setup.sh

### ISSUE THREAD

**Issue by mondherGL** [redhat-cop/aap_configuration_template#28]
Hello , 
 
 i have this error message during execution of  the task ' Run the Ansible Automation Platform setup program': 

fatal: [XXXXXXXX]: FAILED! => {
    "ansible_job_id": "666487507563.1103234",
    "changed": false,
    "cmd": "./setup.sh -i inventory -e upgrade_ansible_with_tower=1 -e web_server_ssl_cert=/root/tower-cert/tower.cert -e web_server_ssl_key=/root/tower-cert/tower.key -e automationhub_ssl_cert=/root/tower-cert/tower.cert -e automationhub_ssl_key=/root/tower-cert/tower.key -e automationhub_api_token=xxxxxxxxxxxxxxxxxx",
    "finished": 1,
    "invocation": {
        "module_args": {
            "_raw_params": "\n./setup.sh -i \"inventory\" -e upgrade_ansible_with_tower=1 -e web_server_ssl_cert=/root/tower-cert/tower.cert -e web_server_ssl_key=/root/tower-cert/tower.key -e automationhub_ssl_cert=/root/tower-cert/tower.cert -e automationhub_ssl_key=/root/tower-cert/tower.key -e automationhub_api_token=xxxxxxx\n",
            "_uses_shell": false,
            "argv": null,
            "chdir": "/tmp/ansible-automation-platform-setup-bundle-2.3-2/",
            "creates": null,
            "executable": null,
            "removes": null,
            "stdin": null,
            "stdin_add_newline": true,
            "strip_empty_ends": true
        }
    },
    "msg": "[Errno 13] Permission denied: b'./setup.sh'",
    "rc": 13,

**Comment by djdanielsson** [comment]
what user are you running this as?

**Comment by mondherGL** [comment]
i was running ./setup.sh (using root ) under /tmp and /tmp was mounted with noexec.

**Comment by djdanielsson** [comment]
thanks for the update
